### ISSUE TITLE
Questions on setup

### ISSUE THREAD

**Issue by packytagliaferro** [synapticism/wordpress-gulp-bower-sass#12]
Just had a few questions on how things were compiled so I can change if needed. 

assetss.php - This is where you load the scripts I see. If I wanted to change the name of the wp-pg8.js file, this file is where its loaded but where do I change it in the gulp so it complies a new name?

AJAX Loading - I love the idea of loading all my pages via ajax. Does this happen by default? I have set WordPress up before so that just the body of the page is loaded (so the nav never flashes or reloads just the content), is this set up the same way or do I have to implement it some how?

Navigation.php - Looks like this just handles nav for posts? 

Navigation.js - this is your mobile menu it looks like. If I change how the nav is handled I assume this is the spot to go to. 

functions-config-defaults.php, functions-config.php - Not sure what these are for. I put some stuff (like hide admin bar) in just the functions.php since thats where I usually have it. These I assume are just if you want to separate custom functions for the bare bones?

Thanks again. This was a real life saver. I dont like how much junk was in all the other "bare bones" solutions.

**Comment by synapticism** [comment]
Re: JS asset loading, you can set filenames in `gulpconfig.js` by editing the `scripts` block. The `wp-` part is defined by the `namespace`. The script name itself (`pg8` in this case) is determined by the name of the script bundle itself. If you change the definition from `pg8: ['pg8', 'core']` to `pageload: ['pg8', 'core']` it should output `wp-pageload.js`.

Re: AJAX loading, no, there's nothing quite so elaborate. The script loaded in the default theme is just a page loader/infinite scroller. To make all page loads by AJAX you'll want to remove that script and use your own.

Re: navigation, yes the PHP temple just handles post navigation since core WP implements no such thing. The `navigation.js` is cribbed from Twenty Twelve or something and yes, if you alter the HTML of the header you'll want to change the IDs of the components that script is meant to act on.

Re: functions setup, that's just a matter of convention. Everything can go in `functions.php` if you want it to. I set things up this way so I can develop a core theme that I use on different sites... at that point I have `functions.php` that does core stuff used on every blog, a `functions-config-defaults.php` with settings shared by all blogs, and then a custom config file on a per-site basis. There's no specific need to do things this way, you can wrap it all up into a single file if it suits your needs.

**Comment by packytagliaferro** [comment]
Thanks you. pg8 is the script I am going to want to remove from the src and also the gulp file correct?

**Comment by synapticism** [comment]
@packytagliaferro Sure, if you don't want it you can just delete anything related to it from `gulpconfig.js` and the asset loading file. The whole point of this project is to make it as easy as possible to add/remove front-end assets :)

**Comment by synapticism** [comment]
OK, I think this has been answered :)
